"""
ELO comparison: GPT vs SEDD generation quality.
Uses OpenAI API (gpt-4o-mini) as judge for pairwise comparisons.

Usage: uv run .run_elo.py
"""

import json
import random
import os
from openai import OpenAI

GPT_PATH = "outputs/gpt_reference.jsonl"
SEDD_PATH = "outputs/sedd_reference.jsonl"
NUM_ROUNDS = 50  # total pairwise comparisons
ELO_K = 32
INITIAL_ELO = 1000

client = OpenAI()

JUDGE_PROMPT = """You are judging the quality of text generated by two language models. You will see a prompt (or "unconditional" if no prompt was given) and two completions labeled A and B.

Rate which completion is better based on:
1. Coherence and fluency (does it read like natural English?)
2. Relevance to the prompt (if prompted)
3. Absence of repetition or gibberish
4. Overall quality

Reply with EXACTLY one of: "A", "B", or "TIE".
Do not explain your reasoning."""


def load_samples(path):
    with open(path) as f:
        return [json.loads(line) for line in f]


def judge(prompt_text, gen_a, gen_b):
    if prompt_text:
        user_msg = f"Prompt: {prompt_text}\n\n--- Completion A ---\n{gen_a[:500]}\n\n--- Completion B ---\n{gen_b[:500]}"
    else:
        user_msg = f"(Unconditional generation, no prompt)\n\n--- Text A ---\n{gen_a[:500]}\n\n--- Text B ---\n{gen_b[:500]}"

    resp = client.chat.completions.create(
        model="gpt-5.4-mini",
        messages=[
            {"role": "system", "content": JUDGE_PROMPT},
            {"role": "user", "content": user_msg},
        ],
        max_completion_tokens=5,
        temperature=0.0,
    )
    answer = resp.choices[0].message.content.strip().upper()
    if "TIE" in answer:
        return "TIE"
    if "A" in answer and "B" not in answer:
        return "A"
    if "B" in answer and "A" not in answer:
        return "B"
    return "TIE"


def update_elo(ra, rb, result):
    ea = 1.0 / (1.0 + 10 ** ((rb - ra) / 400))
    eb = 1.0 - ea
    if result == "A":
        sa, sb = 1.0, 0.0
    elif result == "B":
        sa, sb = 0.0, 1.0
    else:
        sa, sb = 0.5, 0.5
    return ra + ELO_K * (sa - ea), rb + ELO_K * (sb - eb)


def main():
    gpt_samples = load_samples(GPT_PATH)
    sedd_samples = load_samples(SEDD_PATH)

    # Match by type: prompted vs prompted, unconditional vs unconditional
    gpt_prompted = [s for s in gpt_samples if s["type"] == "prompted"]
    gpt_uncond = [s for s in gpt_samples if s["type"] == "unconditional"]
    sedd_prompted = [s for s in sedd_samples if s["type"] == "prompted"]
    sedd_uncond = [s for s in sedd_samples if s["type"] == "unconditional"]

    # Build matchups
    matchups = []
    for i in range(min(len(gpt_prompted), len(sedd_prompted))):
        matchups.append(("prompted", gpt_prompted[i], sedd_prompted[i]))
    for i in range(min(len(gpt_uncond), len(sedd_uncond))):
        matchups.append(("unconditional", gpt_uncond[i], sedd_uncond[i]))

    elo_gpt = INITIAL_ELO
    elo_sedd = INITIAL_ELO
    wins = {"GPT": 0, "SEDD": 0, "TIE": 0}

    print(f"Running {NUM_ROUNDS} pairwise comparisons (GPT vs SEDD)...\n")

    for round_i in range(NUM_ROUNDS):
        m_type, gpt_s, sedd_s = random.choice(matchups)
        prompt = gpt_s.get("prompt", "")

        # Randomly assign A/B to avoid position bias
        if random.random() < 0.5:
            a_label, b_label = "GPT", "SEDD"
            gen_a, gen_b = gpt_s["generated"], sedd_s["generated"]
        else:
            a_label, b_label = "SEDD", "GPT"
            gen_a, gen_b = sedd_s["generated"], gpt_s["generated"]

        result = judge(prompt, gen_a, gen_b)

        # Map back to GPT/SEDD
        if result == "A":
            winner = a_label
        elif result == "B":
            winner = b_label
        else:
            winner = "TIE"

        if winner == "GPT":
            elo_gpt, elo_sedd = update_elo(elo_gpt, elo_sedd, "A")
            wins["GPT"] += 1
        elif winner == "SEDD":
            elo_gpt, elo_sedd = update_elo(elo_gpt, elo_sedd, "B")
            wins["SEDD"] += 1
        else:
            elo_gpt, elo_sedd = update_elo(elo_gpt, elo_sedd, "TIE")
            wins["TIE"] += 1

        print(f"  Round {round_i+1:2d} [{m_type:13s}] winner: {winner:4s} | ELO: GPT={elo_gpt:.0f} SEDD={elo_sedd:.0f}")

    print(f"\n{'='*50}")
    print(f"FINAL ELO RATINGS ({NUM_ROUNDS} rounds)")
    print(f"{'='*50}")
    print(f"  GPT:  {elo_gpt:.0f}")
    print(f"  SEDD: {elo_sedd:.0f}")
    print(f"\nWin counts: GPT={wins['GPT']}, SEDD={wins['SEDD']}, TIE={wins['TIE']}")
    print(f"GPT win rate: {wins['GPT']/NUM_ROUNDS*100:.0f}%")


if __name__ == "__main__":
    main()
